repos:
  - repo: https://github.com/psf/black
    rev: "stable"
    hooks:
      - id: black
        args: ["--line-length", "79", "--safe"]
        language_version: python3.10

  - repo: https://github.com/pycqa/flake8
    rev: ""
    hooks:
      - id: flake8
        args: ["--config", "config.cfg"]

  - repo: https://github.com/pycqa/isort
    rev: ""
    hooks:
      - id: isort
        name: isort (python)
        args: ["--settings-path", "config.cfg"]

  - repo: https://github.com/python-poetry/poetry
    rev: "" # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest -s -v .
        types: [python]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: docs
        name: docs
        stages: [commit]
        language: system
        entry: python -m docs.generate_documentation
        types: [python]
        pass_filenames: false
        always_run: true
