version: "3"

services:
  challenge_db:
    container_name: challenge_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - challenge-network

  challenge_db_admin:
    container_name: db_admin
    depends_on:
      - challenge_db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - challenge-network

  challenge_api:
    container_name: challenge_api
    depends_on:
      - challenge_db
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ENVIRONMENT: "local"
      SK_DB_USER: ${POSTGRES_USER}
      SK_DB_PASS: ${POSTGRES_PASS}
      SK_DB_ENDPOINT: ${POSTGRES_HOST}:${POSTGRES_PORT}
      SK_DB_NAME: ${POSTGRES_DB}
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/src
    networks:
      - challenge-network

networks:
  challenge-network:

volumes:
  pgdata:
  pgadmin:
